# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/hospitaldb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false

# Session timeout (30 minutes)
server.servlet.session.timeout=30m

# JWT
app.jwt.secret=c2VjdXJlLWhvc3BpdGFsLW1hbmFnZW1lbnQtc2VjcmV0LWtleS0yMDI2LWRldjYwMDM=
app.jwt.expiration-ms=3600000

# AES Encryption key for diagnosis (32 chars = 256-bit)
app.encryption.key=HospitalSecure2026AESKey12345678

# Logging
logging.level.com.hospital=DEBUG
logging.level.org.springframework.security=INFO
logging.file.name=logs/hospital-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
