# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:hospitaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false

# Session timeout (30 minutes)
server.servlet.session.timeout=30m

# JWT
app.jwt.secret=c2VjdXJlLWhvc3BpdGFsLW1hbmFnZW1lbnQtc2VjcmV0LWtleS0yMDI2LWRldjYwMDM=
app.jwt.expiration-ms=3600000

# AES Encryption key for diagnosis (32 chars = 256-bit)
app.encryption.key=HospitalSecure2026AESKey12345678

# Logging
logging.level.com.hospital=DEBUG
logging.level.org.springframework.security=INFO
logging.file.name=logs/hospital-app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
